### ISSUE TITLE
Key not found when query contains double quotes

### ISSUE THREAD

**Issue by edwardzjl** [blinxen/tomli#5]
Hi there, I am trying to use tomli to parse containerd config file. There are a lot of quotes in the file, for example:

```toml
[plugins]

  [plugins."io.containerd.gc.v1.scheduler"]
    deletion_threshold = 0
    mutation_threshold = 100
    pause_threshold = 0.02
    schedule_delay = "0s"
    startup_delay = "100ms"
```

However when I use tomli, I encountered the following Key not found error:

```console
# ./tomli query -f config.toml plugins."io.containerd.gc.v1.scheduler".deletion_threshold
Key not found: io
```
